post_install() {

	systemctl daemon-reload &>/dev/null || :
	systemctl enable pured.service &>/dev/null || :
	systemctl start pured.service &>/dev/null || :

	exit 0
}

post_upgrade() {
	post_install
}

pre_remove() {

	systemctl stop pured.service &>/dev/null || :
	systemctl disable pured.service &>/dev/null || :
	systemctl daemon-reload &>/dev/null || :
	rm -rf /etc/purevpn-cli &>/dev/null || :

	exit 0
}

